### ISSUE TITLE
Facing problem while installing this two package 

### ISSUE THREAD

**Issue by uddinnasir** [YubiaoYue/MedMamba#35]
I have CUDA version 11.7, I tried a lot but can not install the two packages, need help thanks, the two libraries are

 pip install causal_conv1d==1.0.0  # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl`
* `pip install mamba_ssm==1.0.1  # mmamba_ssm-1.0.1+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl`

Error is followed 

(mdmamba) root@dfa541618f6d:~/nasir# pip install mamba_ssm==1.0.1
Collecting mamba_ssm==1.0.1
  Using cached mamba_ssm-1.0.1.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hm0h05pe/mamba-ssm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hm0h05pe/mamba-ssm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-run661os
         cwd: /tmp/pip-install-hm0h05pe/mamba-ssm/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hm0h05pe/mamba-ssm/setup.py", line 102, in <module>
        raise RuntimeError(
    RuntimeError: mamba_ssm is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
    
    
    torch.__version__  = 1.13.0+cu117
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rsarka34** [comment]
I am facing the same issue. If you have found the solution please let me know

**Comment by linmoer00** [comment]
需要从官网上下载，再pip install进去，（注意：python=3.8）
