### ISSUE TITLE
Issue with Mamba Transformer Implementation

### ISSUE THREAD

**Issue by SouCh305** [YubiaoYue/MedMamba#39]
I am currently working on a medical image detection problem on the Kaggle platform and attempting to use the Mamba transformer for this task. However, when I ran the code below, I encountered an issue (details provided after the code).

Could someone help me identify the cause of this problem or suggest any fixes?

- Is there a dependency or configuration specific to the Mamba transformer that I might be missing?

- Are there known compatibility issues when using Mamba for medical image detection tasks?

Any advice or guidance would be greatly appreciated. Thank you in advance!

**The code:**
`!pip install einops`
`!pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --extra-index-url https://download.pytorch.org/whl/cu117`
`!pip install packaging`
`!pip install timm==0.4.12`
`!pip install pytest chardet yacs termcolor`
`!pip install submitit tensorboardX`
`!pip install triton==2.0.0`
`!pip install causal-conv1d  # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl`
`!pip install mamba-ssm  # mmamba_ssm-1.0.1+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl`
`!pip install scikit-learn matplotlib thop h5py SimpleITK scikit-image medpy yacs`

**The issue:**

Collecting causal-conv1d
  Downloading causal_conv1d-1.5.0.post8.tar.gz (9.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7lh6rfnr/causal-conv1d_3261fd5c803a42e080e553c8d8af4798/setup.py", line 21, in <module>
          from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME, HIP_HOME
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Collecting mamba-ssm
  Downloading mamba_ssm-2.2.4.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.8/91.8 kB 3.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jb2gu742/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-jb2gu742/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jb2gu742/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
        File "/tmp/pip-build-env-jb2gu742/overlay/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-jb2gu742/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by owo-uu** [comment]
Did you solve your problem? Regarding the issue of "Getting requirements to build wheel did not run successfully", it seems that it cannot be run in Windows environment. I have not found the wheel of the Mamba model in this environment. It seems that it needs to be under Linux operating system. If you can solve this problem or have any good suggestions, can you share it?

**Comment by VDGGZPY** [comment]
if you install your package in ubuntu, you should not use pip commond directly. 
Use following command:
conda install packaging
git clone https://github.com/Dao-AILab/causal-conv1d.git 
cd causal-conv1d 
git checkout v1.2.2 
CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install .

**Comment by VDGGZPY** [comment]
cd ..
git clone https://github.com/state-spaces/mamba.git
cd ./mamba
git checkout v2.0.4
MAMBA_FORCE_BUILD=TRUE pip install .

**Comment by SouCh305** [comment]
I'm currently using the **_Kaggle platform_** to install the Mamba package and run the commands, but I still haven't found a solution to fix the issue.

**Comment by leeminsun1205** [comment]
> I'm currently using the **_Kaggle platform_** to install the Mamba package and run the commands, but I still haven't found a solution to fix the issue.

If you use Kaggle, you can try install this before:
```!pip install mamba-ssm --no-build-isolation```
and then install requirements bellow:
```causal-conv1d>=1.4.0
torch --index-url https://download.pytorch.org/whl/cu121
torchvision
torchaudio 
# Các gói phụ trợ
packaging
# timm==0.4.12
timm
pytest
chardet
yacs
termcolor
submitit
tensorboardX
scikit-learn
matplotlib
triton
thop
h5py
SimpleITK
scikit-image
medpy
```
