### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jxk6575** [YubiaoYue/MedMamba#4]
using cpu device.
Traceback (most recent call last):
  File "/tmp/pycharm_project_185/train.py", line 108, in <module>
    main()
  File "/tmp/pycharm_project_185/train.py", line 27, in main
    train_dataset = datasets.ImageFolder(root='dataset2',
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super().__init__(
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 219, in find_classes
    return find_classes(directory)
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 41, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: 'dataset2'

**Comment by YubiaoYue** [comment]
Hello. It seems that the path to the dataset is incorrect~

**Comment by jxk6575** [comment]
Thanks! I've worked that out but I've got a new problem. If you agree, can you provide your email address just for academic communication? I'm a freshman studying deep learning in Beijing~

**Comment by YubiaoYue** [comment]
Hi! You can find my email adddress in the arxiv paper of **"MedMamba"**.
